# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1470069495);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1470069615);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1470069855);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1470069375);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1469161940);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1470069735);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 36);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1470069600364");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1470071480364");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1470069601280");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1470073201280");
user_pref("browser.search.countryCode", "GT");
user_pref("browser.search.region", "GT");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20160414065514");
user_pref("browser.slowStartup.averageTime", 11734);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20160414065514");
user_pref("browser.startup.homepage_override.mstone", "45.0.2");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\",\"sync-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"pocket-button\",\"downloads-button\",\"home-button\",\"loop-button\"]},\"seen\":[\"loop-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"PanelUI-contents\"],\"currentVersion\":5,\"newElementCount\":0}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1469068509669");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1468982176611");
user_pref("datareporting.policy.firstRunTime", "1468982109668");
user_pref("datareporting.sessions.current.activeTicks", 29);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 13853);
user_pref("datareporting.sessions.current.main", 1039);
user_pref("datareporting.sessions.current.sessionRestored", 12487);
user_pref("datareporting.sessions.current.startTime", "1470069249598");
user_pref("datareporting.sessions.current.totalTime", 1559);
user_pref("datareporting.sessions.currentIndex", 2);
user_pref("datareporting.sessions.prunedIndex", 1);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.bootstrappedAddons", "{\"loop@mozilla.org\":{\"version\":\"1.1.14\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/loop@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", true);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.2,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:45.0.2");
user_pref("extensions.getAddons.cache.lastUpdate", 1470069499);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20160106.01");
user_pref("extensions.lastAppVersion", "45.0.2");
user_pref("extensions.lastPlatformVersion", "45.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"loop@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/loop@mozilla.org.xpi\",\"e\":true,\"v\":\"1.1.14\",\"st\":1460619618000}},\"app-global\":{\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"47.0\",\"st\":1465217641000},\"langpack-es-CL@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-es-CL@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"47.0\",\"st\":1465217647000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"45.0.2\",\"st\":1460619618000},\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"47.0\",\"st\":1465217639000},\"langpack-es-ES@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-es-ES@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"47.0\",\"st\":1465217647000},\"langpack-es-AR@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-es-AR@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"47.0\",\"st\":1465217647000},\"langpack-es-MX@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-es-MX@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"47.0\",\"st\":1465217647000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi\",\"e\":true,\"v\":\"3.2\",\"st\":1442597402000}}}");
user_pref("gecko.buildID", "20160414065514");
user_pref("gecko.mstone", "45.0.2");
user_pref("idle.lastDailyNotification", 1470069318);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1468982179);
user_pref("media.gmp-gmpopenh264.version", "1.5.3");
user_pref("media.gmp-manager.buildID", "20160414065514");
user_pref("media.gmp-manager.lastCheck", 1469161785);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1470069319);
user_pref("places.history.expiration.transient_current_max_pages", 52443);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1468982589);
user_pref("toolkit.startup.last_success", 1470069250);
user_pref("toolkit.telemetry.cachedClientID", "00240485-cca7-473f-9447-32d0f8c7519e");
user_pref("toolkit.telemetry.previousBuildID", "20160414065514");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
