# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-GB@thunderbird.mozilla.org\":{\"version\":\"38.8.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/thunderbird/extensions/langpack-en-GB@thunderbird.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-es-AR@thunderbird.mozilla.org\":{\"version\":\"38.8.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/thunderbird/extensions/langpack-es-AR@thunderbird.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-es-ES@thunderbird.mozilla.org\":{\"version\":\"38.8.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/thunderbird/extensions/langpack-es-ES@thunderbird.mozilla.org.xpi\",\"multiprocessCompatible\":false}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "messagingmenu%40mozilla.com:1.3.1,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:38.8.0");
user_pref("extensions.lastAppVersion", "38.8.0");
user_pref("extensions.lastPlatformVersion", "38.8.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/thunderbird/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"38.8.0\",\"st\":1468710825000,\"mt\":1462989987000},\"langpack-en-GB@thunderbird.mozilla.org\":{\"d\":\"/usr/lib/thunderbird/extensions/langpack-en-GB@thunderbird.mozilla.org.xpi\",\"e\":true,\"v\":\"38.8.0\",\"st\":1462994422000},\"langpack-es-AR@thunderbird.mozilla.org\":{\"d\":\"/usr/lib/thunderbird/extensions/langpack-es-AR@thunderbird.mozilla.org.xpi\",\"e\":true,\"v\":\"38.8.0\",\"st\":1462994425000},\"langpack-es-ES@thunderbird.mozilla.org\":{\"d\":\"/usr/lib/thunderbird/extensions/langpack-es-ES@thunderbird.mozilla.org.xpi\",\"e\":true,\"v\":\"38.8.0\",\"st\":1462994426000},\"messagingmenu@mozilla.com\":{\"d\":\"/usr/lib/thunderbird/extensions/messagingmenu@mozilla.com.xpi\",\"e\":true,\"v\":\"1.3.1\",\"st\":1462990936000}}}");
user_pref("mail.ui-rdf.version", 11);
user_pref("mailnews.database.global.datastore.id", "abdc8d77-7504-4efa-8374-cd547307454");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Importante");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Trabajo");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "Por hacer");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Más tarde");
user_pref("mailnews.tags.version", 2);
user_pref("toolkit.telemetry.previousBuildID", "20160511162223");
